### ISSUE TITLE
Do you use pre-trained word embedding when training infer-sent model on Quora Dataset?

### ISSUE THREAD

**Issue by mapingshuo** [lanwuwei/SPM_toolkit#12]
Hi, I am trying to reproduce your result in the paper: "Neural Network Models for Paraphrase Identification, Semantic Textual Similarity, Natural Language Inference, and Question Answering", where you got 86.6% test acc on Quora dataset with the inferSent model. I wonder whether you use Pre-trained word embedding or not, because the facebook group use Pre-trained word embedding in their paper: "Supervised Learning of Universal Sentence Representations from Natural Language Inference Data".  Thanks.

**Comment by lanwuwei** [comment]
Yes, I used pre-trained GloVe word vectors:
`GLOVE_PATH = basepath + "/pytorch/DeepPairWiseWord/VDPWI-NN-Torch/data/glove/glove.840B.300d.txt"`

**Comment by mapingshuo** [comment]
Thanks for your reply, it's so helpful!
