### ISSUE TITLE
Test results on SNLI from trained model

### ISSUE THREAD

**Issue by aayushee** [lanwuwei/SPM_toolkit#20]
I found a trained ESIM SNLI model in the Google drive folder where preprocessed data is available.
I loaded that model and tested it on the preprocessed test data but got a test accuracy of 58% only. Can someone please tell me if that model is trained or I need to train a model from scratch and then test it?

**Comment by lanwuwei** [comment]
I think you should re-train the model, since the saved model may not correspond to the current code.

**Comment by aayushee** [comment]
I am able to train the model from scratch and it gives good test accuracy.
