### ISSUE TITLE
why i had trained PWIN model and saved it,but it could not be used.

### ISSUE THREAD

**Issue by BruceLee66** [lanwuwei/SPM_toolkit#25]
model=torch.load('model.pkl')
model.eval()
en='This argument is irrational and lacks objectivity.'
it='Tale argomentazione manca di razionalità e di obiettività.'
eng=ps.handle_sen(en,'english')
iti=ps.handle_sen(it,'italian')
a,b=model(eng,iti,1)

**Comment by lanwuwei** [comment]
Bilingual case? You need to make sure the vocabulary has both English and Italian word types, as well as the word embeddings between word index and vector.
