### ISSUE TITLE
If i want to use the sentence pair  model to get the similarity between them?

### ISSUE THREAD

**Issue by BruceLee66** [lanwuwei/SPM_toolkit#27]
Now i have 1000000 sentence pairs,which throw out the same meaning.when i use those data to train the sentence model,i saved the model static pkl. But i use the trained model to eval new sentence pair,almost all of them get the score(1.0) . 
what should i do?can you give me some advice!

**Comment by lanwuwei** [comment]
All positive training examples? no negative?

**Comment by BruceLee66** [comment]
yes. all sentences  pairs are similar. when  I use  this trained  model  to predict  other  sentence pair which is different from each other.its score still  be  very closely to  1.I really confused.

**Comment by lanwuwei** [comment]
You need negative samples for training, otherwise the model will biased towards positive case.

**Comment by BruceLee66** [comment]
I decide to select negative examples randomly. The number of negative samples is 5 times that of the positive example.Would  that be OK?

**Comment by lanwuwei** [comment]
1:1 should be enough. Importantly, you need to make sure the negative examples are meaningful: a pair shared many n-gram words but non-paraphrase.

**Comment by BruceLee66** [comment]
okay!I will try the ratio of 1：1，thank you very much.
