### ISSUE TITLE
test acc for ESIM model on snli testset

### ISSUE THREAD

**Issue by blzhu0823** [lanwuwei/SPM_toolkit#33]
![image](https://user-images.githubusercontent.com/49089185/123832960-7b012280-d938-11eb-9f1c-93017cdc7e67.png)
I just use your trained ESIM model to eval the test acc on snli testset and just get 57.82% acc, which is far below the acc reported on its papar. I don't know why?

**Comment by lanwuwei** [comment]
Hi Bolin,

I think the word embedding index is not matched, just train from scratch, it is not time-consuming.

Best,
Wuwei
