### ISSUE TITLE
ESIM model questions

### ISSUE THREAD

**Issue by blzhu0823** [lanwuwei/SPM_toolkit#34]
I see that 500 epochs need to be trained, do I need to train so many epochs, which will take a long time to train.
![image](https://user-images.githubusercontent.com/49089185/123912681-edf9b000-d9af-11eb-95dc-6f9482d3a371.png)
and I also want to know whether your experimental results close to the original paper.
thanks.

**Comment by lanwuwei** [comment]
No, 500 is a lot, you don't need that many epochs. My reproduced results are not exactly the same as the original paper (~1 point difference), since I didn't do too much hyper-parameter tuning.
