### ISSUE TITLE
Preprocessing?

### ISSUE THREAD

**Issue by andra-pumnea** [lanwuwei/SPM_toolkit#8]
how did you generate a.toks, b.toks and what kind of preprocessing did you apply to questions?

**Comment by lanwuwei** [comment]
Hi andra-pumnea, I followed this [code](https://github.com/stanfordnlp/treelstm/blob/master/scripts/preprocess-sick.py) to do data preprocessing.

**Comment by andra-pumnea** [comment]
cool, thanks!
